on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'src/**.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Compile Java files
        run: |
          mkdir -p bin
          find src -name '*.java' | xargs javac -d bin

      - name: Build JAR file
        run: |
          jar cfe SistemaMedico.jar Main -C bin .

      - name: Delete unnecessary .class files
        run: |
          cd bin
          find . -name '*.class' | while read class_file; do
            java_file=$(echo "$class_file" | sed 's/\.class$/.java/')
            if [ ! -f "../src/$java_file" ]; then
              rm "$class_file"
            fi
          done

      - name: Push JAR file to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: .
          message: Build JAR file

